version: '3.9'

services:
  # Creates self signed tls certificates. Remove if you
  # use your own.

  # Responsible for storing users and their aliases. Remove
  # if you already have a MySQL server.
  db:
    image: jeboehm/mailserver-db:latest
    build: ./db
    restart: on-failure:5
    env_file: .env
    volumes:
      - data-db:/var/lib/mysql

  # The Mail Transfer Agent (Postfix) receives incoming mail
  # on TCP port 25.
  mta:
    # image: jeboehm/mailserver-mta:latest
    build:
      context: ./mta
      dockerfile: Dockerfile
      args:
        buildno: 1
    restart: on-failure:5
    env_file: .env
    volumes:
      # For using external certificates uncomment the following lines
      # and change the path on the left side of the colon.
      - /Volumes/HarrySpace/ssl/tinyinv.com/fullchain.pem:/media/tls/mailserver.crt:ro
      - /Volumes/HarrySpace/ssl/tinyinv.com/privkey.pem:/media/tls/mailserver.key:ro
      - /Volumes/HarrySpace/ssl/saigontiny.com/fullchain.pem:/media/tls/saigontiny.crt:ro
      - /Volumes/HarrySpace/ssl/saigontiny.com/privkey.pem:/media/tls/saigontiny.key:ro

  # The Mail Delivery Agent (Dovecot) is responsible for storing
  # incoming mail into a users mailbox and also delivers them
  # via POP3 or IMAP4.
  mda:
    # image: jeboehm/mailserver-mda:latest
    build:
      context: ./mda
      dockerfile: Dockerfile
      args:
        buildno: 1
    restart: on-failure:5
    env_file: .env
    volumes:
      - data-mail:/var/vmail
      # For using external certificates uncomment the following lines
      # and change the path on the left side of the colon.
      - /Volumes/HarrySpace/ssl/tinyinv.com/fullchain.pem:/media/tls/mailserver.crt:ro
      - /Volumes/HarrySpace/ssl/tinyinv.com/privkey.pem:/media/tls/mailserver.key:ro
      - /Volumes/HarrySpace/ssl/saigontiny.com/fullchain.pem:/media/tls/saigontiny.crt:ro
      - /Volumes/HarrySpace/ssl/saigontiny.com/privkey.pem:/media/tls/saigontiny.key:ro
      # - ./mda/custom/10-ssl.conf:/etc/dovecot/conf.d/10-ssl.conf

  # The admin (mailserver-admin) and webmail (roundcube) interfaces
  # live here. Can be removed if not needed.
  web:
    image: jeboehm/mailserver-web:latest
    # build: ./web
    restart: on-failure:5
    env_file: .env
    volumes:
      - data-dkim:/media/dkim
    # For use with jwilder/nginx-proxy.
    # environment:
    #   - VIRTUAL_HOST=mail.example.com

  # Incoming spam is (hopefully) filtered by rspamd which runs
  # in this service.
  filter:
    image: jeboehm/mailserver-filter:latest
    # build: ./filter
    restart: on-failure:5
    env_file: .env
    volumes:
      - data-filter:/var/lib/rspamd
      - data-dkim:/media/dkim
    links:
      - virus:virus.local

  # Incoming viruses or malware is detected and rejected by
  # this service. Can be removed if FILTER_VIRUS is set to false.
  virus:
    image: jeboehm/mailserver-virus:latest
    # build: ./virus
    restart: on-failure:5
    env_file: .env
    volumes:
      - data-virusdb:/var/lib/clamav

  # If you want unhealthy containers to be restarted automatically
  # just uncomment the following lines.
  # autoheal:
  #   image: willfarrell/autoheal:latest
  #   restart: always
  #   networks: []
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #   environment:
  #     - AUTOHEAL_CONTAINER_LABEL=de.ressourcenkonflikt.docker-mailserver.autoheal

  # Optional service: extend ClamAV (used in the virus service)
  # by downloading additional databases provided by different
  # companys. Run it regulary.
  # virus_unof_sig_updater:
  #   build: ./virus/contrib/unofficial-sigs
  #   env_file: .env
  #   volumes:
  #     - data-virusdb:/var/lib/clamav

volumes:
  data-db:
  data-dkim:
  data-mail:
  data-tls:
  data-filter:
  data-virusdb:
